spring.application.name=backend

# ===== Servidor =====
server.port=8089

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/mantenedor_usuarios
spring.datasource.username=postgres
spring.datasource.password=admin123

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
app.jwt.secret=ClaveSecretaSuperLargaParaFirmarTokensJWT1234567890ABCDEFGH
app.jwt.expiration-ms=86400000
